<?php

/*
 * Base de datos central de universidades de Colombia.
 * Este archivo es incluido tanto por universidades.php (pagina central)
 * como por universidad_ciudad.php (pagina de detalle por ciudad).
 */

return [
    [
        'id' => 'udea',
        'nombre' => 'Universidad de Antioquia',
        'ciudad' => 'Medellín',
        'tipo' => 'Pública',
        'fundacion' => '1803',
        'web' => 'https://www.udea.edu.co',
        'descripcion' => 'La Universidad de Antioquia (UdeA) es una de las universidades públicas más importantes y antiguas de Colombia, reconocida por su investigación en salud, ciencias y humanidades.',
        'carreras' => [
            [
                'nombre' => 'Medicina',
                'duracion' => '12 semestres',
                'titulo' => 'Médico(a)',
                'trata' => 'Diagnóstico, tratamiento y prevención de enfermedades en el cuerpo humano.',
                'campo' => 'Hospitales, clínicas, salud pública e investigación médica.',
            ],
            [
                'nombre' => 'Ingeniería de Sistemas',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) de Sistemas',
                'trata' => 'Desarrollo de software, redes, bases de datos e inteligencia artificial.',
                'campo' => 'Empresas de tecnología, desarrollo de software y ciberseguridad.',
            ],
            [
                'nombre' => 'Derecho',
                'duracion' => '10 semestres',
                'titulo' => 'Abogado(a)',
                'trata' => 'Estudio de las leyes, la justicia y las normas que rigen la sociedad.',
                'campo' => 'Juzgados, notarías, empresas y litigio independiente.',
            ],
        ],
    ],
    [
        'id' => 'eafit',
        'nombre' => 'Universidad EAFIT',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1960',
        'web' => 'https://www.eafit.edu.co',
        'descripcion' => 'EAFIT es una universidad privada de Medellín reconocida por sus programas de negocios, ingeniería y su fuerte enfoque en innovación y emprendimiento.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería de Sistemas',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) de Sistemas',
                'trata' => 'Programación, ciencia de datos, inteligencia artificial y desarrollo de software.',
                'campo' => 'Empresas tecnológicas, startups y consultoría en TI.',
            ],
            [
                'nombre' => 'Negocios Internacionales',
                'duracion' => '9 semestres',
                'titulo' => 'Profesional en Negocios Internacionales',
                'trata' => 'Comercio exterior, finanzas globales y estrategia empresarial.',
                'campo' => 'Multinacionales, comercio exterior y consultoría.',
            ],
            [
                'nombre' => 'Diseño',
                'duracion' => '9 semestres',
                'titulo' => 'Diseñador(a)',
                'trata' => 'Diseño gráfico, industrial y de experiencia de usuario.',
                'campo' => 'Agencias creativas, empresas de producto y marcas.',
            ],
        ],
    ],
    [
        'id' => 'upb',
        'nombre' => 'Universidad Pontificia Bolivariana',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1936',
        'web' => 'https://www.upb.edu.co',
        'descripcion' => 'La UPB es una universidad privada de tradición católica, con gran oferta en ingenierías, comunicación y ciencias de la salud.',
        'carreras' => [
            [
                'nombre' => 'Comunicación Social',
                'duracion' => '9 semestres',
                'titulo' => 'Comunicador(a) Social',
                'trata' => 'Periodismo, producción audiovisual y medios digitales.',
                'campo' => 'Televisión, radio, agencias de contenido y medios digitales.',
            ],
            [
                'nombre' => 'Ingeniería Industrial',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Industrial',
                'trata' => 'Optimización de procesos productivos y gestión de calidad.',
                'campo' => 'Manufactura, logística y consultoría de procesos.',
            ],
        ],
    ],
    [
        'id' => 'udem',
        'nombre' => 'Universidad de Medellín',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1950',
        'web' => 'https://www.udem.edu.co',
        'descripcion' => 'Universidad privada con amplia oferta en ingenierías, derecho, economía y ciencias sociales, con fuerte presencia regional.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Civil',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Civil',
                'trata' => 'Diseño y construcción de infraestructura como puentes, edificios y vías.',
                'campo' => 'Constructoras, entidades públicas y consultoría estructural.',
            ],
            [
                'nombre' => 'Economía',
                'duracion' => '9 semestres',
                'titulo' => 'Economista',
                'trata' => 'Análisis de mercados, políticas públicas y finanzas.',
                'campo' => 'Bancos, entidades gubernamentales y consultoría económica.',
            ],
        ],
    ],
    [
        'id' => 'unal-medellin',
        'nombre' => 'Universidad Nacional (Sede Medellín)',
        'ciudad' => 'Medellín',
        'tipo' => 'Pública',
        'fundacion' => '1936',
        'web' => 'https://medellin.unal.edu.co',
        'descripcion' => 'Sede de la Universidad Nacional de Colombia en Medellín, reconocida por sus programas de ingeniería, arquitectura y ciencias agropecuarias.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería de Minas',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) de Minas',
                'trata' => 'Exploración, extracción y aprovechamiento de recursos minerales.',
                'campo' => 'Empresas mineras, energéticas y de consultoría ambiental.',
            ],
            [
                'nombre' => 'Arquitectura',
                'duracion' => '10 semestres',
                'titulo' => 'Arquitecto(a)',
                'trata' => 'Diseño de espacios, edificaciones y planeación urbana.',
                'campo' => 'Firmas de arquitectura, entidades públicas y construcción.',
            ],
        ],
    ],
    [
        'id' => 'itm',
        'nombre' => 'Instituto Tecnológico Metropolitano (ITM)',
        'ciudad' => 'Medellín',
        'tipo' => 'Pública',
        'fundacion' => '1993',
        'web' => 'https://www.itm.edu.co',
        'descripcion' => 'Institución universitaria pública de Medellín con enfoque técnico y tecnológico, accesible y orientada a las necesidades del sector productivo.',
        'carreras' => [
            [
                'nombre' => 'Tecnología en Análisis y Desarrollo de Software',
                'duracion' => '6 semestres',
                'titulo' => 'Tecnólogo(a) en Software',
                'trata' => 'Programación, bases de datos y desarrollo de aplicaciones.',
                'campo' => 'Empresas de software, soporte técnico y desarrollo web.',
            ],
        ],
    ],
    [
        'id' => 'sena',
        'nombre' => 'SENA',
        'ciudad' => 'Medellín (nacional)',
        'tipo' => 'Pública (gratuita)',
        'fundacion' => '1957',
        'web' => 'https://www.sena.edu.co',
        'descripcion' => 'El SENA ofrece formación técnica y tecnológica gratuita en todo el país, con alta empleabilidad y convenios con empresas.',
        'carreras' => [
            [
                'nombre' => 'Análisis y Desarrollo de Software',
                'duracion' => '2 años',
                'titulo' => 'Tecnólogo(a) ADSO',
                'trata' => 'Programación, bases de datos y desarrollo de software.',
                'campo' => 'Empresas de tecnología, desarrollo web y soporte.',
            ],
            [
                'nombre' => 'Gestión Empresarial',
                'duracion' => '2 años',
                'titulo' => 'Tecnólogo(a) en Gestión Empresarial',
                'trata' => 'Administración, contabilidad básica y procesos empresariales.',
                'campo' => 'Pymes, áreas administrativas y emprendimiento.',
            ],
        ],
    ],
    [
        'id' => 'unal-bogota',
        'nombre' => 'Universidad Nacional de Colombia (Sede Bogotá)',
        'ciudad' => 'Bogotá',
        'tipo' => 'Pública',
        'fundacion' => '1867',
        'web' => 'https://www.unal.edu.co',
        'descripcion' => 'La universidad pública más importante del país, con la mayor oferta académica e investigativa a nivel nacional.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería de Sistemas',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) de Sistemas',
                'trata' => 'Desarrollo de software, inteligencia artificial y sistemas tecnológicos.',
                'campo' => 'Empresas tecnológicas, desarrollo web y ciberseguridad.',
            ],
            [
                'nombre' => 'Psicología',
                'duracion' => '10 semestres',
                'titulo' => 'Psicólogo(a)',
                'trata' => 'Comportamiento humano, emociones y salud mental.',
                'campo' => 'Hospitales, colegios, empresas y consultorios.',
            ],
        ],
    ],
    [
        'id' => 'andes',
        'nombre' => 'Universidad de los Andes',
        'ciudad' => 'Bogotá',
        'tipo' => 'Privada',
        'fundacion' => '1948',
        'web' => 'https://uniandes.edu.co',
        'descripcion' => 'Una de las universidades privadas más prestigiosas y costosas de Colombia, reconocida a nivel internacional en negocios, ingeniería y derecho.',
        'carreras' => [
            [
                'nombre' => 'Administración de Empresas',
                'duracion' => '9 semestres',
                'titulo' => 'Administrador(a)',
                'trata' => 'Liderazgo, finanzas y gestión empresarial.',
                'campo' => 'Empresas, marketing y emprendimiento.',
            ],
            [
                'nombre' => 'Derecho',
                'duracion' => '10 semestres',
                'titulo' => 'Abogado(a)',
                'trata' => 'Estudio de leyes, justicia y normas sociales.',
                'campo' => 'Firmas de abogados, litigio y sector público.',
            ],
        ],
    ],
    [
        'id' => 'javeriana',
        'nombre' => 'Pontificia Universidad Javeriana',
        'ciudad' => 'Bogotá',
        'tipo' => 'Privada',
        'fundacion' => '1623',
        'web' => 'https://www.javeriana.edu.co',
        'descripcion' => 'Universidad privada de tradición jesuita, una de las más antiguas de América, con fuerte oferta en salud, comunicación y humanidades.',
        'carreras' => [
            [
                'nombre' => 'Comunicación Social',
                'duracion' => '8 semestres',
                'titulo' => 'Comunicador(a) Social',
                'trata' => 'Medios de comunicación, periodismo y producción audiovisual.',
                'campo' => 'Televisión, radio y medios digitales.',
            ],
            [
                'nombre' => 'Medicina',
                'duracion' => '12 semestres',
                'titulo' => 'Médico(a)',
                'trata' => 'Diagnóstico y tratamiento de enfermedades.',
                'campo' => 'Hospitales, clínicas y salud pública.',
            ],
        ],
    ],
    [
        'id' => 'rosario',
        'nombre' => 'Universidad del Rosario',
        'ciudad' => 'Bogotá',
        'tipo' => 'Privada',
        'fundacion' => '1653',
        'web' => 'https://www.urosario.edu.co',
        'descripcion' => 'Una de las universidades más antiguas de Colombia, con gran prestigio en derecho, medicina y ciencias políticas.',
        'carreras' => [
            [
                'nombre' => 'Derecho',
                'duracion' => '10 semestres',
                'titulo' => 'Abogado(a)',
                'trata' => 'Estudio de leyes, justicia y normatividad.',
                'campo' => 'Juzgados, empresas y sector público.',
            ],
        ],
    ],
    [
        'id' => 'externado',
        'nombre' => 'Universidad Externado de Colombia',
        'ciudad' => 'Bogotá',
        'tipo' => 'Privada',
        'fundacion' => '1886',
        'web' => 'https://www.uexternado.edu.co',
        'descripcion' => 'Reconocida especialmente por sus programas de derecho, ciencias políticas y economía.',
        'carreras' => [
            [
                'nombre' => 'Ciencia Política',
                'duracion' => '8 semestres',
                'titulo' => 'Politólogo(a)',
                'trata' => 'Análisis de sistemas políticos, gobierno y políticas públicas.',
                'campo' => 'Entidades públicas, ONG y organismos internacionales.',
            ],
        ],
    ],
    [
        'id' => 'icesi',
        'nombre' => 'Universidad Icesi',
        'ciudad' => 'Cali',
        'tipo' => 'Privada',
        'fundacion' => '1979',
        'web' => 'https://www.icesi.edu.co',
        'descripcion' => 'Universidad privada del suroccidente colombiano, reconocida por su enfoque innovador en negocios e ingeniería.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Industrial',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) Industrial',
                'trata' => 'Optimización de procesos y gestión de recursos.',
                'campo' => 'Manufactura, logística y consultoría.',
            ],
        ],
    ],
    [
        'id' => 'univalle',
        'nombre' => 'Universidad del Valle',
        'ciudad' => 'Cali',
        'tipo' => 'Pública',
        'fundacion' => '1945',
        'web' => 'https://www.univalle.edu.co',
        'descripcion' => 'Principal universidad pública del suroccidente colombiano, con fuerte tradición en salud e ingeniería.',
        'carreras' => [
            [
                'nombre' => 'Medicina',
                'duracion' => '12 semestres',
                'titulo' => 'Médico(a)',
                'trata' => 'Diagnóstico y tratamiento de enfermedades.',
                'campo' => 'Hospitales y salud pública.',
            ],
        ],
    ],
    [
        'id' => 'unorte',
        'nombre' => 'Universidad del Norte',
        'ciudad' => 'Barranquilla',
        'tipo' => 'Privada',
        'fundacion' => '1966',
        'web' => 'https://www.uninorte.edu.co',
        'descripcion' => 'La universidad privada más importante de la región Caribe, con fuerte oferta en ingenierías y negocios.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Industrial',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Industrial',
                'trata' => 'Gestión de procesos productivos y calidad.',
                'campo' => 'Industria, logística y consultoría.',
            ],
        ],
    ],
    [
        'id' => 'uis',
        'nombre' => 'Universidad Industrial de Santander (UIS)',
        'ciudad' => 'Bucaramanga',
        'tipo' => 'Pública',
        'fundacion' => '1948',
        'web' => 'https://www.uis.edu.co',
        'descripcion' => 'Universidad pública líder en Santander, reconocida por sus programas de ingeniería y ciencias.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería de Petróleos',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) de Petróleos',
                'trata' => 'Exploración y explotación de hidrocarburos.',
                'campo' => 'Empresas petroleras y energéticas.',
            ],
        ],
    ],
    [
        'id' => 'utb',
        'nombre' => 'Universidad Tecnológica de Bolívar',
        'ciudad' => 'Cartagena',
        'tipo' => 'Privada',
        'fundacion' => '1970',
        'web' => 'https://www.utb.edu.co',
        'descripcion' => 'Universidad privada de la costa Caribe con fuerte enfoque en ingeniería y negocios marítimos.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Naval',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) Naval',
                'trata' => 'Diseño y mantenimiento de embarcaciones y estructuras marítimas.',
                'campo' => 'Industria naval y portuaria.',
            ],
        ],
    ],
    [
        'id' => 'ces',
        'nombre' => 'Universidad CES',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1977',
        'web' => 'https://www.ces.edu.co',
        'descripcion' => 'Universidad privada de Medellín reconocida a nivel nacional por sus programas del área de la salud y su enfoque investigativo.',
        'carreras' => [
            [
                'nombre' => 'Medicina',
                'duracion' => '12 semestres',
                'titulo' => 'Médico(a)',
                'trata' => 'Formación clínica integral con énfasis en investigación biomédica.',
                'campo' => 'Hospitales, clínicas, investigación y salud pública.',
            ],
            [
                'nombre' => 'Odontología',
                'duracion' => '10 semestres',
                'titulo' => 'Odontólogo(a)',
                'trata' => 'Prevención, diagnóstico y tratamiento de enfermedades bucales.',
                'campo' => 'Clínicas odontológicas, consultorios privados y salud pública.',
            ],
        ],
    ],
    [
        'id' => 'eia',
        'nombre' => 'Escuela de Ingeniería de Antioquia (EIA)',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1970',
        'web' => 'https://www.eia.edu.co',
        'descripcion' => 'Institución privada especializada exclusivamente en ingenierías, reconocida por su alta exigencia académica y vínculo con el sector productivo.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Biomédica',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Biomédico(a)',
                'trata' => 'Diseño de tecnología y dispositivos aplicados a la salud.',
                'campo' => 'Hospitales, empresas de dispositivos médicos e investigación.',
            ],
            [
                'nombre' => 'Ingeniería Administrativa',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Administrador(a)',
                'trata' => 'Gestión de procesos, proyectos y organizaciones con enfoque técnico.',
                'campo' => 'Empresas industriales, consultoría y gerencia de proyectos.',
            ],
        ],
    ],
    [
        'id' => 'lasallista',
        'nombre' => 'Corporación Universitaria Lasallista',
        'ciudad' => 'Medellín (Caldas)',
        'tipo' => 'Privada',
        'fundacion' => '1983',
        'web' => 'https://www.lasallista.edu.co',
        'descripcion' => 'Universidad privada del área metropolitana de Medellín, reconocida por sus programas de ingeniería de alimentos, administración y ciencias agropecuarias.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería de Alimentos',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) de Alimentos',
                'trata' => 'Procesamiento, conservación y control de calidad de alimentos.',
                'campo' => 'Industria alimentaria, control de calidad e investigación.',
            ],
        ],
    ],
    [
        'id' => 'sanbuenaventura',
        'nombre' => 'Universidad de San Buenaventura (Medellín)',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1968',
        'web' => 'https://www.usbmed.edu.co',
        'descripcion' => 'Universidad privada de tradición franciscana con oferta en ingenierías, educación, comunicación y ciencias sociales.',
        'carreras' => [
            [
                'nombre' => 'Psicología',
                'duracion' => '10 semestres',
                'titulo' => 'Psicólogo(a)',
                'trata' => 'Estudio del comportamiento humano y procesos mentales.',
                'campo' => 'Clínicas, colegios, empresas y consultorios particulares.',
            ],
        ],
    ],
    [
        'id' => 'funlam',
        'nombre' => 'Universidad Católica Luis Amigó (FUNLAM)',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1986',
        'web' => 'https://www.funlam.edu.co',
        'descripcion' => 'Universidad privada con enfoque social, reconocida por sus programas en ciencias sociales, comunicación y criminología.',
        'carreras' => [
            [
                'nombre' => 'Criminología',
                'duracion' => '9 semestres',
                'titulo' => 'Criminólogo(a)',
                'trata' => 'Estudio del delito, la criminalidad y la seguridad ciudadana.',
                'campo' => 'Policía, fiscalía, entidades de seguridad e investigación.',
            ],
        ],
    ],
    [
        'id' => 'unaula',
        'nombre' => 'Universidad Autónoma Latinoamericana (UNAULA)',
        'ciudad' => 'Medellín',
        'tipo' => 'Privada',
        'fundacion' => '1966',
        'web' => 'https://www.unaula.edu.co',
        'descripcion' => 'Universidad privada de Medellín con tradición en programas sociales, jurídicos y humanísticos, orientada a la accesibilidad.',
        'carreras' => [
            [
                'nombre' => 'Derecho',
                'duracion' => '10 semestres',
                'titulo' => 'Abogado(a)',
                'trata' => 'Formación jurídica con enfoque en derechos humanos y justicia social.',
                'campo' => 'Juzgados, defensoría pública, litigio y sector social.',
            ],
        ],
    ],
    [
        'id' => 'colmayor',
        'nombre' => 'Colegio Mayor de Antioquia',
        'ciudad' => 'Medellín',
        'tipo' => 'Pública',
        'fundacion' => '1945',
        'web' => 'https://www.colmayor.edu.co',
        'descripcion' => 'Institución universitaria pública de Medellín, con programas técnicos, tecnológicos y profesionales accesibles.',
        'carreras' => [
            [
                'nombre' => 'Gastronomía',
                'duracion' => '8 semestres',
                'titulo' => 'Profesional en Gastronomía',
                'trata' => 'Preparación de alimentos, gestión de cocina y cultura culinaria.',
                'campo' => 'Restaurantes, hotelería y emprendimiento gastronómico.',
            ],
        ],
    ],
    [
        'id' => 'politecnico-jic',
        'nombre' => 'Politécnico Colombiano Jaime Isaza Cadavid',
        'ciudad' => 'Medellín',
        'tipo' => 'Pública',
        'fundacion' => '1964',
        'web' => 'https://www.elpoli.edu.co',
        'descripcion' => 'Institución universitaria pública de Medellín con amplia oferta técnica, tecnológica y profesional a precios accesibles.',
        'carreras' => [
            [
                'nombre' => 'Tecnología en Sistemas',
                'duracion' => '6 semestres',
                'titulo' => 'Tecnólogo(a) en Sistemas',
                'trata' => 'Desarrollo, soporte y mantenimiento de sistemas informáticos.',
                'campo' => 'Empresas de tecnología, soporte técnico y desarrollo de software.',
            ],
        ],
    ],
    [
        'id' => 'unimilitar',
        'nombre' => 'Universidad Militar Nueva Granada',
        'ciudad' => 'Bogotá',
        'tipo' => 'Pública',
        'fundacion' => '1938',
        'web' => 'https://www.umng.edu.co',
        'descripcion' => 'Universidad pública adscrita al Ministerio de Defensa, con oferta académica abierta al público civil además de personal militar.',
        'carreras' => [
            [
                'nombre' => 'Relaciones Internacionales y Estudios Políticos',
                'duracion' => '9 semestres',
                'titulo' => 'Profesional en Relaciones Internacionales',
                'trata' => 'Análisis de política exterior, diplomacia y seguridad internacional.',
                'campo' => 'Cancillería, organismos internacionales y sector diplomático.',
            ],
        ],
    ],
    [
        'id' => 'distrital',
        'nombre' => 'Universidad Distrital Francisco José de Caldas',
        'ciudad' => 'Bogotá',
        'tipo' => 'Pública',
        'fundacion' => '1948',
        'web' => 'https://www.udistrital.edu.co',
        'descripcion' => 'Universidad pública de Bogotá reconocida por su fuerte oferta en ingenierías, educación y artes, con matrícula muy accesible.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Electrónica',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Electrónico(a)',
                'trata' => 'Diseño de sistemas electrónicos, telecomunicaciones y automatización.',
                'campo' => 'Empresas de tecnología, telecomunicaciones e industria.',
            ],
        ],
    ],
    [
        'id' => 'santotomas',
        'nombre' => 'Universidad Santo Tomás',
        'ciudad' => 'Bogotá',
        'tipo' => 'Privada',
        'fundacion' => '1580',
        'web' => 'https://www.usta.edu.co',
        'descripcion' => 'Una de las universidades más antiguas de Colombia, de tradición dominica, con amplia oferta en derecho, ingeniería y ciencias sociales.',
        'carreras' => [
            [
                'nombre' => 'Derecho',
                'duracion' => '10 semestres',
                'titulo' => 'Abogado(a)',
                'trata' => 'Formación jurídica integral con enfoque humanista.',
                'campo' => 'Juzgados, litigio, sector público y privado.',
            ],
        ],
    ],
    [
        'id' => 'sergioarboleda',
        'nombre' => 'Universidad Sergio Arboleda',
        'ciudad' => 'Bogotá',
        'tipo' => 'Privada',
        'fundacion' => '1965',
        'web' => 'https://www.usergioarboleda.edu.co',
        'descripcion' => 'Universidad privada reconocida por sus programas de derecho, comunicación, negocios y relaciones internacionales.',
        'carreras' => [
            [
                'nombre' => 'Periodismo',
                'duracion' => '8 semestres',
                'titulo' => 'Periodista',
                'trata' => 'Investigación, redacción y producción de contenido informativo.',
                'campo' => 'Medios de comunicación, prensa y medios digitales.',
            ],
        ],
    ],
    [
        'id' => 'sabana',
        'nombre' => 'Universidad de La Sabana',
        'ciudad' => 'Bogotá (Chía)',
        'tipo' => 'Privada',
        'fundacion' => '1979',
        'web' => 'https://www.unisabana.edu.co',
        'descripcion' => 'Universidad privada de alta calidad ubicada en las afueras de Bogotá, reconocida por su enfoque en formación integral.',
        'carreras' => [
            [
                'nombre' => 'Enfermería',
                'duracion' => '9 semestres',
                'titulo' => 'Enfermero(a) Profesional',
                'trata' => 'Cuidado integral de la salud de pacientes en distintos contextos.',
                'campo' => 'Hospitales, clínicas y salud comunitaria.',
            ],
        ],
    ],
    [
        'id' => 'piloto',
        'nombre' => 'Universidad Piloto de Colombia',
        'ciudad' => 'Bogotá',
        'tipo' => 'Privada',
        'fundacion' => '1962',
        'web' => 'https://www.unipiloto.edu.co',
        'descripcion' => 'Universidad privada reconocida especialmente por sus programas de arquitectura, diseño e ingeniería.',
        'carreras' => [
            [
                'nombre' => 'Arquitectura',
                'duracion' => '10 semestres',
                'titulo' => 'Arquitecto(a)',
                'trata' => 'Diseño y planeación de espacios urbanos y edificaciones.',
                'campo' => 'Firmas de arquitectura, construcción y entidades públicas.',
            ],
        ],
    ],
    [
        'id' => 'usc',
        'nombre' => 'Universidad Santiago de Cali',
        'ciudad' => 'Cali',
        'tipo' => 'Privada',
        'fundacion' => '1958',
        'web' => 'https://www.usc.edu.co',
        'descripcion' => 'Universidad privada del suroccidente colombiano con amplia oferta en salud, derecho e ingeniería.',
        'carreras' => [
            [
                'nombre' => 'Fisioterapia',
                'duracion' => '9 semestres',
                'titulo' => 'Fisioterapeuta',
                'trata' => 'Rehabilitación y prevención de lesiones del movimiento humano.',
                'campo' => 'Hospitales, clínicas de rehabilitación y deporte.',
            ],
        ],
    ],
    [
        'id' => 'uao',
        'nombre' => 'Universidad Autónoma de Occidente',
        'ciudad' => 'Cali',
        'tipo' => 'Privada',
        'fundacion' => '1970',
        'web' => 'https://www.uao.edu.co',
        'descripcion' => 'Universidad privada de Cali reconocida por su oferta en comunicación, ingeniería y ciencias ambientales.',
        'carreras' => [
            [
                'nombre' => 'Comunicación Publicitaria',
                'duracion' => '9 semestres',
                'titulo' => 'Publicista',
                'trata' => 'Creación de estrategias y campañas de mercadeo y publicidad.',
                'campo' => 'Agencias de publicidad, marketing digital y empresas.',
            ],
        ],
    ],
    [
        'id' => 'javeriana-cali',
        'nombre' => 'Pontificia Universidad Javeriana (Cali)',
        'ciudad' => 'Cali',
        'tipo' => 'Privada',
        'fundacion' => '1970',
        'web' => 'https://www.javerianacali.edu.co',
        'descripcion' => 'Sede de la Universidad Javeriana en Cali, con fuerte oferta en salud, ingeniería y ciencias económicas.',
        'carreras' => [
            [
                'nombre' => 'Medicina',
                'duracion' => '12 semestres',
                'titulo' => 'Médico(a)',
                'trata' => 'Formación médica integral con enfoque humanista.',
                'campo' => 'Hospitales, clínicas y salud pública.',
            ],
        ],
    ],
    [
        'id' => 'uniatlantico',
        'nombre' => 'Universidad del Atlántico',
        'ciudad' => 'Barranquilla',
        'tipo' => 'Pública',
        'fundacion' => '1941',
        'web' => 'https://www.uniatlantico.edu.co',
        'descripcion' => 'Principal universidad pública de la región Caribe, con amplia oferta académica a bajo costo.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Química',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Químico(a)',
                'trata' => 'Procesos de transformación de materias primas en productos industriales.',
                'campo' => 'Industria petroquímica, manufactura y consultoría ambiental.',
            ],
        ],
    ],
    [
        'id' => 'unicartagena',
        'nombre' => 'Universidad de Cartagena',
        'ciudad' => 'Cartagena',
        'tipo' => 'Pública',
        'fundacion' => '1827',
        'web' => 'https://www.unicartagena.edu.co',
        'descripcion' => 'Una de las universidades públicas más antiguas de Colombia, con fuerte tradición en salud y derecho.',
        'carreras' => [
            [
                'nombre' => 'Odontología',
                'duracion' => '10 semestres',
                'titulo' => 'Odontólogo(a)',
                'trata' => 'Diagnóstico y tratamiento de enfermedades bucodentales.',
                'campo' => 'Clínicas odontológicas y salud pública.',
            ],
        ],
    ],
    [
        'id' => 'unab',
        'nombre' => 'Universidad Autónoma de Bucaramanga (UNAB)',
        'ciudad' => 'Bucaramanga',
        'tipo' => 'Privada',
        'fundacion' => '1952',
        'web' => 'https://www.unab.edu.co',
        'descripcion' => 'Universidad privada líder en Santander, con oferta en ingeniería, salud, comunicación y ciencias económicas.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería de Sistemas',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) de Sistemas',
                'trata' => 'Desarrollo de software y soluciones tecnológicas.',
                'campo' => 'Empresas de tecnología y desarrollo de software.',
            ],
        ],
    ],
    [
        'id' => 'ustabucaramanga',
        'nombre' => 'Universidad Santo Tomás (Bucaramanga)',
        'ciudad' => 'Bucaramanga',
        'tipo' => 'Privada',
        'fundacion' => '1976',
        'web' => 'https://www.ustabuca.edu.co',
        'descripcion' => 'Sede de la Universidad Santo Tomás en Bucaramanga, con amplia oferta en ingeniería, salud y ciencias sociales.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Ambiental',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Ambiental',
                'trata' => 'Gestión y conservación de recursos naturales y control de la contaminación.',
                'campo' => 'Entidades ambientales, consultoría y sector industrial.',
            ],
        ],
    ],
    [
        'id' => 'unal-manizales',
        'nombre' => 'Universidad Nacional (Sede Manizales)',
        'ciudad' => 'Manizales',
        'tipo' => 'Pública',
        'fundacion' => '1948',
        'web' => 'https://www.manizales.unal.edu.co',
        'descripcion' => 'Sede de la Universidad Nacional en el Eje Cafetero, reconocida por sus programas de ingeniería y ciencias agroindustriales.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Física',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Físico(a)',
                'trata' => 'Aplicación de principios físicos al diseño de tecnología e instrumentación.',
                'campo' => 'Investigación, industria tecnológica y desarrollo de instrumentos.',
            ],
        ],
    ],
    [
        'id' => 'ucaldas',
        'nombre' => 'Universidad de Caldas',
        'ciudad' => 'Manizales',
        'tipo' => 'Pública',
        'fundacion' => '1943',
        'web' => 'https://www.ucaldas.edu.co',
        'descripcion' => 'Universidad pública del departamento de Caldas, con fuerte oferta en salud, agronomía y ciencias sociales.',
        'carreras' => [
            [
                'nombre' => 'Zootecnia',
                'duracion' => '9 semestres',
                'titulo' => 'Zootecnista',
                'trata' => 'Producción, manejo y mejoramiento de especies animales.',
                'campo' => 'Sector agropecuario, industria pecuaria e investigación.',
            ],
        ],
    ],
    [
        'id' => 'autonoma-manizales',
        'nombre' => 'Universidad Autónoma de Manizales',
        'ciudad' => 'Manizales',
        'tipo' => 'Privada',
        'fundacion' => '1979',
        'web' => 'https://www.autonoma.edu.co',
        'descripcion' => 'Universidad privada del Eje Cafetero reconocida por su enfoque en salud, ingeniería y ciencias administrativas.',
        'carreras' => [
            [
                'nombre' => 'Fisioterapia',
                'duracion' => '9 semestres',
                'titulo' => 'Fisioterapeuta',
                'trata' => 'Rehabilitación física y prevención de lesiones.',
                'campo' => 'Clínicas de rehabilitación, hospitales y deporte.',
            ],
        ],
    ],
    [
        'id' => 'utp',
        'nombre' => 'Universidad Tecnológica de Pereira (UTP)',
        'ciudad' => 'Pereira',
        'tipo' => 'Pública',
        'fundacion' => '1958',
        'web' => 'https://www.utp.edu.co',
        'descripcion' => 'Universidad pública líder del Eje Cafetero, reconocida por su oferta en ingenierías, medicina y ciencias ambientales.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Mecánica',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Mecánico(a)',
                'trata' => 'Diseño, fabricación y mantenimiento de sistemas mecánicos.',
                'campo' => 'Industria manufacturera, automotriz y energética.',
            ],
        ],
    ],
    [
        'id' => 'uniquindio',
        'nombre' => 'Universidad del Quindío',
        'ciudad' => 'Armenia',
        'tipo' => 'Pública',
        'fundacion' => '1961',
        'web' => 'https://www.uniquindio.edu.co',
        'descripcion' => 'Principal universidad pública del Quindío, con oferta en salud, educación e ingeniería.',
        'carreras' => [
            [
                'nombre' => 'Biología',
                'duracion' => '9 semestres',
                'titulo' => 'Biólogo(a)',
                'trata' => 'Estudio de los seres vivos, ecosistemas y biodiversidad.',
                'campo' => 'Investigación, entidades ambientales y educación.',
            ],
        ],
    ],
    [
        'id' => 'unibague',
        'nombre' => 'Universidad de Ibagué',
        'ciudad' => 'Ibagué',
        'tipo' => 'Privada',
        'fundacion' => '1980',
        'web' => 'https://www.unibague.edu.co',
        'descripcion' => 'Universidad privada del Tolima con oferta en ingeniería, negocios, música y ciencias sociales.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Agroindustrial',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) Agroindustrial',
                'trata' => 'Transformación y aprovechamiento de productos agrícolas.',
                'campo' => 'Industria alimentaria, agroindustria y exportaciones.',
            ],
        ],
    ],
    [
        'id' => 'unitolima',
        'nombre' => 'Universidad del Tolima',
        'ciudad' => 'Ibagué',
        'tipo' => 'Pública',
        'fundacion' => '1945',
        'web' => 'https://www.ut.edu.co',
        'descripcion' => 'Universidad pública del Tolima con fuerte tradición en agronomía, educación y ciencias de la salud.',
        'carreras' => [
            [
                'nombre' => 'Agronomía',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Agrónomo(a)',
                'trata' => 'Producción agrícola sostenible y manejo de cultivos.',
                'campo' => 'Sector agropecuario, agroindustria e investigación.',
            ],
        ],
    ],
    [
        'id' => 'usco',
        'nombre' => 'Universidad Surcolombiana',
        'ciudad' => 'Neiva',
        'tipo' => 'Pública',
        'fundacion' => '1968',
        'web' => 'https://www.usco.edu.co',
        'descripcion' => 'Principal universidad pública del Huila, con oferta en salud, ingeniería y educación.',
        'carreras' => [
            [
                'nombre' => 'Medicina',
                'duracion' => '12 semestres',
                'titulo' => 'Médico(a)',
                'trata' => 'Diagnóstico y tratamiento de enfermedades.',
                'campo' => 'Hospitales y salud pública regional.',
            ],
        ],
    ],
    [
        'id' => 'unicauca',
        'nombre' => 'Universidad del Cauca',
        'ciudad' => 'Popayán',
        'tipo' => 'Pública',
        'fundacion' => '1827',
        'web' => 'https://www.unicauca.edu.co',
        'descripcion' => 'Una de las universidades públicas más antiguas y prestigiosas del suroccidente colombiano, reconocida en ingeniería electrónica y medicina.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Electrónica y Telecomunicaciones',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Electrónico(a)',
                'trata' => 'Diseño de sistemas de comunicación y electrónica avanzada.',
                'campo' => 'Telecomunicaciones, investigación y tecnología.',
            ],
        ],
    ],
    [
        'id' => 'udenar',
        'nombre' => 'Universidad de Nariño',
        'ciudad' => 'Pasto',
        'tipo' => 'Pública',
        'fundacion' => '1904',
        'web' => 'https://www.udenar.edu.co',
        'descripcion' => 'Principal universidad pública del departamento de Nariño, con oferta en agronomía, salud e ingeniería.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Agroforestal',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Agroforestal',
                'trata' => 'Manejo sostenible de sistemas agrícolas y forestales.',
                'campo' => 'Sector agropecuario, entidades ambientales e investigación.',
            ],
        ],
    ],
    [
        'id' => 'ufps',
        'nombre' => 'Universidad Francisco de Paula Santander',
        'ciudad' => 'Cúcuta',
        'tipo' => 'Pública',
        'fundacion' => '1962',
        'web' => 'https://www.ufps.edu.co',
        'descripcion' => 'Principal universidad pública de Norte de Santander, con amplia oferta en ingeniería, salud y educación.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Civil',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Civil',
                'trata' => 'Diseño y construcción de infraestructura vial y de edificaciones.',
                'campo' => 'Constructoras y entidades públicas de infraestructura.',
            ],
        ],
    ],
    [
        'id' => 'unillanos',
        'nombre' => 'Universidad de los Llanos',
        'ciudad' => 'Villavicencio',
        'tipo' => 'Pública',
        'fundacion' => '1974',
        'web' => 'https://www.unillanos.edu.co',
        'descripcion' => 'Principal universidad pública de la región de la Orinoquía, con fuerte oferta en ciencias agropecuarias y ambientales.',
        'carreras' => [
            [
                'nombre' => 'Medicina Veterinaria y Zootecnia',
                'duracion' => '10 semestres',
                'titulo' => 'Médico(a) Veterinario(a) Zootecnista',
                'trata' => 'Salud, manejo y producción de animales domésticos y de granja.',
                'campo' => 'Clínicas veterinarias, sector pecuario e investigación.',
            ],
        ],
    ],
    [
        'id' => 'unicordoba',
        'nombre' => 'Universidad de Córdoba',
        'ciudad' => 'Montería',
        'tipo' => 'Pública',
        'fundacion' => '1966',
        'web' => 'https://www.unicordoba.edu.co',
        'descripcion' => 'Principal universidad pública del departamento de Córdoba, con fuerte tradición en ciencias agropecuarias y salud.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Agronómica',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Agrónomo(a)',
                'trata' => 'Producción agrícola y manejo sostenible de cultivos tropicales.',
                'campo' => 'Sector agropecuario e investigación agrícola.',
            ],
        ],
    ],
    [
        'id' => 'unisucre',
        'nombre' => 'Universidad de Sucre',
        'ciudad' => 'Sincelejo',
        'tipo' => 'Pública',
        'fundacion' => '1976',
        'web' => 'https://www.unisucre.edu.co',
        'descripcion' => 'Principal universidad pública del departamento de Sucre, con oferta en salud, ingeniería y ciencias agropecuarias.',
        'carreras' => [
            [
                'nombre' => 'Enfermería',
                'duracion' => '9 semestres',
                'titulo' => 'Enfermero(a) Profesional',
                'trata' => 'Cuidado integral de la salud individual y comunitaria.',
                'campo' => 'Hospitales, centros de salud y salud pública.',
            ],
        ],
    ],
    [
        'id' => 'unicesar',
        'nombre' => 'Universidad Popular del Cesar',
        'ciudad' => 'Valledupar',
        'tipo' => 'Pública',
        'fundacion' => '1976',
        'web' => 'https://www.unicesar.edu.co',
        'descripcion' => 'Principal universidad pública del departamento del Cesar, con oferta en ingeniería, educación y ciencias administrativas.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Agroindustrial',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) Agroindustrial',
                'trata' => 'Transformación de productos agropecuarios en bienes de consumo.',
                'campo' => 'Agroindustria, exportaciones y control de calidad.',
            ],
        ],
    ],
    [
        'id' => 'uniguajira',
        'nombre' => 'Universidad de La Guajira',
        'ciudad' => 'Riohacha',
        'tipo' => 'Pública',
        'fundacion' => '1976',
        'web' => 'https://www.uniguajira.edu.co',
        'descripcion' => 'Principal universidad pública del departamento de La Guajira, con programas orientados al desarrollo regional.',
        'carreras' => [
            [
                'nombre' => 'Administración de Empresas',
                'duracion' => '9 semestres',
                'titulo' => 'Administrador(a) de Empresas',
                'trata' => 'Gestión, liderazgo y dirección de organizaciones.',
                'campo' => 'Empresas privadas, sector público y emprendimiento.',
            ],
        ],
    ],
    [
        'id' => 'unimagdalena',
        'nombre' => 'Universidad del Magdalena',
        'ciudad' => 'Santa Marta',
        'tipo' => 'Pública',
        'fundacion' => '1958',
        'web' => 'https://www.unimagdalena.edu.co',
        'descripcion' => 'Principal universidad pública del Magdalena, reconocida por su crecimiento en investigación e ingeniería.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Pesquera',
                'duracion' => '9 semestres',
                'titulo' => 'Ingeniero(a) Pesquero(a)',
                'trata' => 'Manejo sostenible de recursos marinos y acuicultura.',
                'campo' => 'Sector pesquero, acuicultura e investigación marina.',
            ],
        ],
    ],
    [
        'id' => 'uptc',
        'nombre' => 'Universidad Pedagógica y Tecnológica de Colombia (UPTC)',
        'ciudad' => 'Tunja',
        'tipo' => 'Pública',
        'fundacion' => '1953',
        'web' => 'https://www.uptc.edu.co',
        'descripcion' => 'Universidad pública de Boyacá con amplia oferta en educación, ingeniería y ciencias agropecuarias.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Metalúrgica',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Metalúrgico(a)',
                'trata' => 'Procesamiento y transformación de materiales metálicos.',
                'campo' => 'Industria minera, siderúrgica y manufactura.',
            ],
        ],
    ],
    [
        'id' => 'utch',
        'nombre' => 'Universidad Tecnológica del Chocó',
        'ciudad' => 'Quibdó',
        'tipo' => 'Pública',
        'fundacion' => '1968',
        'web' => 'https://www.utch.edu.co',
        'descripcion' => 'Principal universidad pública del Chocó, con programas orientados al desarrollo de la región del Pacífico.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Ambiental',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Ambiental',
                'trata' => 'Gestión y conservación de ecosistemas y recursos naturales.',
                'campo' => 'Entidades ambientales, ONG e investigación.',
            ],
        ],
    ],
    [
        'id' => 'uniamazonia',
        'nombre' => 'Universidad de la Amazonia',
        'ciudad' => 'Florencia',
        'tipo' => 'Pública',
        'fundacion' => '1982',
        'web' => 'https://www.udla.edu.co',
        'descripcion' => 'Principal universidad pública de la región amazónica colombiana, con enfoque en ciencias agropecuarias y ambientales.',
        'carreras' => [
            [
                'nombre' => 'Ingeniería Agroecológica',
                'duracion' => '10 semestres',
                'titulo' => 'Ingeniero(a) Agroecológico(a)',
                'trata' => 'Producción agrícola sostenible en armonía con los ecosistemas.',
                'campo' => 'Sector agropecuario, entidades ambientales e investigación.',
            ],
        ],
    ],
];
